import React from 'react';
import { Project, ProjectStatus } from '../types';
import { Plus, Search, Filter, Sparkles } from 'lucide-react';
import ChatAssistant from './ChatAssistant';

interface ProjectListProps {
    projects: Project[];
    onSelectProject: (id: string) => void;
    onAddProject: (p: Partial<Project>) => void;
}

const ProjectList: React.FC<ProjectListProps> = ({ projects, onSelectProject, onAddProject }) => {
    const [showModal, setShowModal] = React.useState(false);
    const [newProject, setNewProject] = React.useState<Partial<Project>>({
        name: '',
        description: '',
        budget: 0,
        startDate: '',
        endDate: '',
        status: ProjectStatus.DRAFT
    });
    const [isGenerating, setIsGenerating] = React.useState(false);
    const [isChatOpen, setIsChatOpen] = React.useState(false);

    const handleGenerateIdea = async () => {
        if (!newProject.name) return;
        setIsGenerating(true);
        await new Promise(r => setTimeout(r, 1500));
        setNewProject(prev => ({
            ...prev,
            description: `Proposed project scope for ${prev.name}: This initiative aims to deliver strategic value by... (Generated by Gemini)`
        }));
        setIsGenerating(false);
    };

    const getStatusColor = (status: ProjectStatus) => {
        switch (status) {
            case ProjectStatus.ACTIVE: return 'bg-green-100 text-green-700';
            case ProjectStatus.DRAFT: return 'bg-gray-100 text-gray-700';
            case ProjectStatus.ON_HOLD: return 'bg-orange-100 text-orange-700';
            case ProjectStatus.COMPLETED: return 'bg-blue-100 text-blue-700';
            default: return 'bg-gray-100 text-gray-700';
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900">Projects</h1>
                    <p className="text-sm text-gray-500">Manage your project portfolio</p>
                </div>
                <button
                    onClick={() => setShowModal(true)}
                    className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 shadow-sm transition-colors"
                >
                    <Plus size={18} />
                    New Project
                </button>
            </div>

            <div className="bg-white rounded-xl shadow-sm border border-gray-200 overflow-hidden">
                <div className="p-4 border-b border-gray-200 flex flex-col sm:flex-row gap-4 bg-gray-50/50">
                    <div className="relative flex-1">
                        <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18} />
                        <input
                            type="text"
                            placeholder="Search projects by code or name..."
                            className="w-full pl-10 pr-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none"
                        />
                    </div>
                    <button className="flex items-center gap-2 px-4 py-2 border border-gray-300 rounded-lg bg-white text-gray-700 hover:bg-gray-50">
                        <Filter size={18} />
                        Filter
                    </button>
                </div>

                <div className="overflow-x-auto">
                    <table className="w-full text-left">
                        <thead className="bg-gray-50 text-gray-500 font-medium text-xs uppercase tracking-wider">
                            <tr>
                                <th className="px-6 py-4">Code</th>
                                <th className="px-6 py-4">Project Name</th>
                                <th className="px-6 py-4">Manager</th>
                                <th className="px-6 py-4">Timeline</th>
                                <th className="px-6 py-4">Budget</th>
                                <th className="px-6 py-4">Status</th>
                                <th className="px-6 py-4">Progress</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-gray-200">
                            {projects.map((project) => (
                                <tr
                                    key={project.id}
                                    onClick={() => onSelectProject(project.id)}
                                    className="hover:bg-blue-50 cursor-pointer transition-colors group"
                                >
                                    <td className="px-6 py-4 text-sm font-medium text-gray-900">{project.code}</td>
                                    <td className="px-6 py-4">
                                        <div className="text-sm font-semibold text-gray-900 group-hover:text-blue-600">{project.name}</div>
                                        <div className="text-xs text-gray-500 truncate max-w-[200px]">{project.description}</div>
                                    </td>
                                    <td className="px-6 py-4 text-sm text-gray-600">Bob Manager</td>
                                    <td className="px-6 py-4 text-sm text-gray-600">
                                        {new Date(project.startDate).toLocaleDateString()} - {new Date(project.endDate).toLocaleDateString()}
                                    </td>
                                    <td className="px-6 py-4 text-sm text-gray-900 font-medium">${project.budget.toLocaleString()}</td>
                                    <td className="px-6 py-4">
                                        <span className={`px-2.5 py-1 rounded-full text-xs font-medium border ${getStatusColor(project.status).replace('text', 'border-transparent')}`}>
                                            {project.status.replace('_', ' ')}
                                        </span>
                                    </td>
                                    <td className="px-6 py-4">
                                        <div className="flex items-center gap-2">
                                            <div className="w-20 bg-gray-200 rounded-full h-2">
                                                <div className="bg-blue-600 h-2 rounded-full" style={{ width: `${project.progress}%` }}></div>
                                            </div>
                                            <span className="text-xs text-gray-500">{project.progress}%</span>
                                        </div>
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </div>

            {showModal && (
                <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-50 p-4">
                    <div className="bg-white rounded-xl shadow-xl max-w-lg w-full p-6">
                        <h2 className="text-xl font-bold mb-4">Initiate New Project</h2>
                        <div className="space-y-4">
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Project Name</label>
                                <input
                                    type="text"
                                    className="w-full border rounded-lg p-2"
                                    value={newProject.name}
                                    onChange={e => setNewProject({ ...newProject, name: e.target.value })}
                                />
                            </div>
                            <div>
                                <label className="block text-sm font-medium text-gray-700 mb-1">Description</label>
                                <div className="relative">
                                    <textarea
                                        className="w-full border rounded-lg p-2 h-24"
                                        value={newProject.description}
                                        onChange={e => setNewProject({ ...newProject, description: e.target.value })}
                                        placeholder="Describe the project scope..."
                                    />
                                    <button
                                        onClick={() => setIsChatOpen(true)}
                                        className="absolute bottom-2 right-2 text-xs bg-purple-600 text-white px-3 py-1.5 rounded-full hover:bg-purple-700 flex items-center gap-1.5 shadow-sm transition-all hover:scale-105 active:scale-95"
                                    >
                                        <Sparkles size={14} />
                                        AI Assistant
                                    </button>
                                </div>
                            </div>
                            <div className="grid grid-cols-2 gap-4">
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Budget ($)</label>
                                    <input
                                        type="number"
                                        className="w-full border rounded-lg p-2"
                                        value={newProject.budget}
                                        onChange={e => setNewProject({ ...newProject, budget: parseInt(e.target.value) })}
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">Start Date</label>
                                    <input
                                        type="date"
                                        className="w-full border rounded-lg p-2"
                                        value={newProject.startDate}
                                        onChange={e => setNewProject({ ...newProject, startDate: e.target.value })}
                                    />
                                </div>
                                <div>
                                    <label className="block text-sm font-medium text-gray-700 mb-1">End Date</label>
                                    <input
                                        type="date"
                                        className="w-full border rounded-lg p-2"
                                        value={newProject.endDate}
                                        onChange={e => setNewProject({ ...newProject, endDate: e.target.value })}
                                    />
                                </div>
                            </div>
                        </div>
                        <div className="mt-6 flex justify-end gap-3">
                            <button onClick={() => setShowModal(false)} className="px-4 py-2 text-gray-600 hover:bg-gray-100 rounded-lg">Cancel</button>
                            <button
                                onClick={() => { onAddProject(newProject); setShowModal(false); }}
                                className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
                            >
                                Create Project
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <ChatAssistant
                isOpen={isChatOpen}
                onClose={() => setIsChatOpen(false)}
                onApplyText={(text) => {
                    setNewProject(prev => ({ ...prev, description: text }));
                    setIsChatOpen(false);
                }}
            />
        </div>
    );
};

export default ProjectList;